name: "Feature Request"
description: Suggest a idea for improvement or new functionality
title: "[Feature]: "
labels: ["Type: Feature"]
projects: ["operationalCommandTeam/1"]
body:
  - type: markdown
    attributes:
      value: |
        Have an idea? Please describe it clearly so we can evaluate and prioritize.
  - type: input
    id: summary
    attributes:
      label: Summary
      description: Short description of the feature
      placeholder: "Add a new map mode"
    validations:
      required: true
  - type: textarea
    id: motivation
    attributes:
      label: Motivation
      description: Why is this feature needed? What problem does it solve?
    validations:
      required: true
  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: How would you like to see this implemented?
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Did you consider other solutions?
  - type: textarea
    id: notes
    attributes:
      label: Additional Notes
      description: Any extra information, references, or mockups?
